In [1]:
import pandas as pd

#yelp_business = pd.read_json('yelp_academic_dataset_business.json')


# read the entire file into a python array
with open('yelp_academic_dataset_business.json', 'rb') as f:
    data = f.readlines()

# remove the trailing "\n" from each line
data = map(lambda x: x.rstrip(), data)

# each element of 'data' is an individual JSON object.
# i want to convert it into an *array* of JSON objects
# which, in and of itself, is one large JSON object
# basically... add square brackets to the beginning
# and end, and have all the individual business JSON objects
# separated by a comma
data_json_str = b'[' + b','.join(data) + b']'

# now, load it into pandas
data_df = pd.read_json(data_json_str)

In [2]:
rest_data_df = data_df[['Restaurants' in x for x in data_df['categories']]]
az_rest_data_df = rest_data_df[['AZ' in x for x in rest_data_df['state']]]

In [3]:
import numpy as np

zip_code = [];


for index,rest in az_rest_data_df.iterrows():
    address = rest['full_address'].split('AZ ')
    if len(address) == 2:
        zip_code.append(int(address[1]))
    else:
        zip_code.append(np.nan)

az_rest_data_df['zip_code'] = zip_code

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [4]:
az_rest_data_df.head()

,attributes,business_id,categories,city,full_address,hours,latitude,longitude,name,neighborhoods,open,review_count,stars,state,type,zip_code
2216,"{'Attire': 'casual', 'Caters': False, 'Price R...",x5Mv61CnZLohZWxfCVCPTQ,"[Sandwiches, Pizza, Chicken Wings, Restaurants]",Phoenix,"2819 N Central Ave\nPhoenix, AZ 85004","{'Friday': {'open': '10:00', 'close': '02:00'}...",33.479482,-112.073681,Domino's Pizza,[],True,16,2.5,AZ,business,85004.0
2217,"{'Takes Reservations': False, 'Price Range': 1...",2ZnCITVa0abGce4gZ6RhIw,"[American (New), Sandwiches, Restaurants]",Phoenix,"1850 N Central Ave\nPhoenix, AZ 85004",{},33.468547,-112.075085,Viad Tower Restaurants,[],True,6,3.5,AZ,business,85004.0
2218,"{'Attire': 'casual', 'Ages Allowed': '21plus',...",EmzaQR5hQlF0WIl24NxAZA,"[American (New), Nightlife, Dance Clubs, Resta...",Phoenix,"132 E Washington St\nPhoenix, AZ 85004","{'Friday': {'open': '09:00', 'close': '03:00'}...",33.448399,-112.071702,Sky Lounge,[],True,25,2.5,AZ,business,85004.0
2222,"{'Attire': 'casual', 'Caters': True, 'Price Ra...",KPoTixdjoJxSqRSEApSAGg,"[Thai, Restaurants]",Phoenix,"2631 N Central Ave\nPhoenix, AZ 85004","{'Friday': {'open': '11:00', 'close': '22:00'}...",33.477939,-112.073417,Wild Thaiger,[],True,432,3.5,AZ,business,85004.0
2230,"{'Attire': 'casual', 'Caters': True, 'Price Ra...",e5kc0CQ4R-PCCDgb274gSg,"[Cafes, Mexican, Tex-Mex, Restaurants]",Phoenix,"455 N 3rd St\nSte 114\nPhoenix, AZ 85004","{'Friday': {'open': '11:00', 'close': '22:00'}...",33.452154,-112.068620,Canyon Cafe,[],True,238,3.5,AZ,business,85004.0

In [17]:
colnames = ['zip','total population']
census_data = pd.read_csv('ACS_14_5YR_DP05.csv',
                   names=colnames, sep=',', quoting=1)
census_data = census_data[1::4]

zips = [];

for row in census_data['zip']:
    address = row.split('A5')
    zips.append(int(address[1]))

census_data['zip_code'] = zips

census_data = census_data.reset_index(drop=True)
census_data.head()

           zip total population  zip_code
0  ZCTA5 84531              920     84531
1  ZCTA5 84536             1998     84536
2  ZCTA5 85003             9262     85003
3  ZCTA5 85004             4649     85004
4  ZCTA5 85006            26473     85006

In [44]:
#census_data.to_csv('census.csv', sep=',')

In [18]:
frame = census_data.iloc[:,(1,2)]
az_rest_data = pd.merge(az_rest_data_df,frame,how ='left', on = 'zip_code')

az_rest_data.to_csv('arizona_restaurants_vs_population.csv', sep = ',')
az_rest_data.head()

,attributes,business_id,categories,city,full_address,hours,latitude,longitude,name,neighborhoods,open,review_count,stars,state,type,zip_code,total population
0,"{'Attire': 'casual', 'Caters': False, 'Price R...",x5Mv61CnZLohZWxfCVCPTQ,"[Sandwiches, Pizza, Chicken Wings, Restaurants]",Phoenix,"2819 N Central Ave\nPhoenix, AZ 85004","{'Friday': {'open': '10:00', 'close': '02:00'}...",33.479482,-112.073681,Domino's Pizza,[],True,16,2.5,AZ,business,85004.0,4649
1,"{'Takes Reservations': False, 'Price Range': 1...",2ZnCITVa0abGce4gZ6RhIw,"[American (New), Sandwiches, Restaurants]",Phoenix,"1850 N Central Ave\nPhoenix, AZ 85004",{},33.468547,-112.075085,Viad Tower Restaurants,[],True,6,3.5,AZ,business,85004.0,4649
2,"{'Attire': 'casual', 'Ages Allowed': '21plus',...",EmzaQR5hQlF0WIl24NxAZA,"[American (New), Nightlife, Dance Clubs, Resta...",Phoenix,"132 E Washington St\nPhoenix, AZ 85004","{'Friday': {'open': '09:00', 'close': '03:00'}...",33.448399,-112.071702,Sky Lounge,[],True,25,2.5,AZ,business,85004.0,4649
3,"{'Attire': 'casual', 'Caters': True, 'Price Ra...",KPoTixdjoJxSqRSEApSAGg,"[Thai, Restaurants]",Phoenix,"2631 N Central Ave\nPhoenix, AZ 85004","{'Friday': {'open': '11:00', 'close': '22:00'}...",33.477939,-112.073417,Wild Thaiger,[],True,432,3.5,AZ,business,85004.0,4649
4,"{'Attire': 'casual', 'Caters': True, 'Price Ra...",e5kc0CQ4R-PCCDgb274gSg,"[Cafes, Mexican, Tex-Mex, Restaurants]",Phoenix,"455 N 3rd St\nSte 114\nPhoenix, AZ 85004","{'Friday': {'open': '11:00', 'close': '22:00'}...",33.452154,-112.068620,Canyon Cafe,[],True,238,3.5,AZ,business,85004.0,4649

In [ ]:
nan_count = 0
for i, row in az_rest_data.iterrows():
    if row['income'] != row['income']:
        nan_count = nan_count + 1